### ISSUE TITLE
Example / Greenlock broken

### ISSUE THREAD

**Issue by RevolvingDCON** [nodecraft/acme-dns-01-cloudflare#14] opened 2020-06-01 09:27 UTC
Using the Greenlock v4 example, it returns: ` UnhandledPromiseRejectionWarning: Error: missing 'packageAgent' and also failed to read `name` and/or 'version' from 'package.json'`

There's also no documentation on Greenlock v4 so I'm not entirely sure how to debug this..

Edit: Formatting

**Comment by Rautherdir** [comment] 2020-06-01 15:55
This is caused by both not specifying a packageAgent when calling Greenlock.create, and not having a package.json file containing either a 'name' or a 'version' field, (which Greenlock uses to create a default packageAgent if it isn't specified)

I'll see if I can update that Greenlock v4 example to have packageAgent with it's default value though, which should help prevent this from being an issue in the future.

**Comment by RevolvingDCON** [comment] 2020-06-01 16:00
Awesome thanks! I understand this is not an issue thread for Greenlock, however I had since added the packageAgent as per their example yet it still failed. You don't happen to know if greenlock is still actively being developed do you?

**Comment by Rautherdir** [comment] 2020-06-01 16:22
I'm not sure if it's still being actively developed or not, a 4 month hiatus isn't unheard of. If you added packageAgent the way it's specified in their example, you'll need a package.json file in your project. (preferably with name and version, so it doesn't set the packageAgent to just '/')

**Comment by Cherry** [comment] 2020-07-31 20:48
I'm going to close this as I believe it was resolved in #15. Feel free to open a new issue if you run into any other problems!

**Closed by Cherry** 2020-07-31 20:48 UTC
Labels: documentation
